// Loader for skatteutgifter master list and fact rows.
//
// Sources:
//   scripts/skatteutgifter/master-list.json  — generated by parse-bilaga.ts
//                                               from data/skr-2025-98.txt.
//                                               Contains every item from the
//                                               regeringens skatteutgifts-
//                                               bilaga (~150 rows).
//   scripts/skatteutgifter/extras.ts         — hand-maintained items that
//                                               are NOT in the bilaga but
//                                               are publicly interesting
//                                               (ränteavdraget).
//   data/skatteutgifter-bilaga.csv           — generated by parse-bilaga.ts,
//                                               3-year values for every item.
//
// To refresh the dataset after a new bilaga is published:
//   1. curl -sLo data/skr-20YY-98.pdf "https://www.regeringen.se/..."
//   2. pdftotext -layout data/skr-20YY-98.pdf data/skr-20YY-98.txt
//   3. point parse-bilaga.ts at the new txt file, bump section heading if needed
//   4. bun scripts/skatteutgifter/parse-bilaga.ts
//   5. bun scripts/skatteutgifter/seed-skatteutgifter.ts
//
// Adding an "extra" item (not in bilaga): edit extras.ts, then re-run seeder.

import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { SkatteutgiftDef, SkatteutgiftFact } from './types.ts';
import { EXTRA_DIMS, EXTRA_FACTS } from './extras.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface MasterListJsonRow extends SkatteutgiftDef {
  section: string;
}

async function loadMasterListFromJson(): Promise<SkatteutgiftDef[]> {
  const jsonPath = resolve(__dirname, 'master-list.json');
  if (!existsSync(jsonPath)) {
    throw new Error(
      `master-list.json missing. Run: bun scripts/skatteutgifter/parse-bilaga.ts`,
    );
  }
  const raw = await readFile(jsonPath, 'utf8');
  const rows = JSON.parse(raw) as MasterListJsonRow[];
  // Strip the `section` field — it's only a hint for the parser.
  return rows.map(({ section: _section, ...def }) => def);
}

export async function getMasterList(): Promise<SkatteutgiftDef[]> {
  const bilaga = await loadMasterListFromJson();
  return [...bilaga, ...EXTRA_DIMS];
}

/**
 * Load fact rows from the bilaga CSV + extras.ts. Returns [] if no CSV.
 */
export async function loadFacts(repoRoot: string): Promise<SkatteutgiftFact[]> {
  const facts: SkatteutgiftFact[] = [];

  const csvPath = resolve(repoRoot, 'data', 'skatteutgifter-bilaga.csv');
  if (!existsSync(csvPath)) {
    console.warn(
      `[skatteutgifter] No CSV at ${csvPath} — run parse-bilaga.ts first.`,
    );
  } else {
    const text = await readFile(csvPath, 'utf8');
    const lines = text.split(/\r?\n/).filter(l => l.trim() && !l.startsWith('#'));
    if (lines.length > 0) {
      const header = lines[0].split(',').map(h => h.trim());
      const idx = {
        year: header.indexOf('year'),
        code: header.indexOf('code'),
        amount: header.indexOf('amount_mkr'),
        est: header.indexOf('is_estimated'),
      };
      if (idx.year < 0 || idx.code < 0 || idx.amount < 0) {
        throw new Error(
          `skatteutgifter-bilaga.csv: missing required columns. Got: ${header.join(',')}`,
        );
      }
      for (const line of lines.slice(1)) {
        const cols = line.split(',').map(c => c.trim());
        facts.push({
          year: parseInt(cols[idx.year], 10),
          code: cols[idx.code],
          amount_mkr: parseFloat(cols[idx.amount]),
          is_estimated: idx.est >= 0 ? cols[idx.est].toLowerCase() === 'true' : false,
        });
      }
    }
  }

  facts.push(...EXTRA_FACTS);
  return facts;
}
